In [1]:
import scipy.io as scio 
import numpy as np
import matplotlib.pyplot as plt
import skimage as ski
from skimage.color import rgb2grey
from sklearn.feature_extraction import image
import skimage.measure
from sklearn.mixture import GaussianMixture
from sklearn import mixture

In [2]:
pavia = {'rgb': scio.loadmat('PaviaRGB.mat')['PaviaRGB'],
         'color_map' : scio.loadmat('PaviaColorMap.mat')['PaviaColorMap'],
         'ground_truth' : scio.loadmat('PaviaGrTruth.mat')['PaviaGrTruth'],
         'ground_truth_mask' : scio.loadmat('PaviaGrTruthMask.mat')['PaviaGrTruthMask'],
         'wavelengths' : scio.loadmat('PaviaWavelengths.mat')['PaviaWavelengths'],
        }
sanbar = {'rgb': scio.loadmat('SanBarRGB.mat')['SanBarRGB'],
          'wavelengths': scio.loadmat('SanBarWavelengths.mat')['WaveLengths'],
          'hyperimage': scio.loadmat('SanBarHyperIm.mat')['SanBarIm88x400'],
         }

In [53]:
Img = pavia['rgb']
[l,w,h] = Img.shape
x = np.reshape(Img,(l*w,h))

In [56]:
Img.shape

(610, 340, 3)

In [58]:
gmm = mixture.GaussianMixture(n_components=10, covariance_type='full', max_iter=20, random_state=0)
gmm.fit(x)

GaussianMixture(covariance_type='full', init_params='kmeans', max_iter=20,
        means_init=None, n_components=10, n_init=1, precisions_init=None,
        random_state=0, reg_covar=1e-06, tol=0.001, verbose=0,
        verbose_interval=10, warm_start=False, weights_init=None)

In [59]:
print(gmm.means_)
print(gmm.covariances_)

[[103.38089081 101.63617548  91.32683377]
 [ 39.65848126  64.74403577  36.4695182 ]
 [115.88208022 209.23027341 215.98904289]
 [159.53534198 151.95083297 122.55158729]
 [ 18.84328869  33.99027941  25.06165213]
 [101.76234754  90.27730871  62.63468859]
 [138.34690767  99.19791968  76.83977284]
 [ 72.87261087  73.9930689   47.3568242 ]
 [134.12119801 127.31134597 103.96527188]
 [ 71.42161206  89.62554965  87.57883597]]
[[[ 218.44834089  136.20151481   69.64009593]
  [ 136.20151481  163.51332826  124.35860816]
  [  69.64009593  124.35860816  171.5544945 ]]

 [[  94.49364774   58.85674317   36.44977986]
  [  58.85674317  262.34061134   48.65037665]
  [  36.44977986   48.65037665   64.74725578]]

 [[2218.58079577  625.11645801  327.48309052]
  [ 625.11645801  788.70435984  618.57009879]
  [ 327.48309052  618.57009879  558.16954054]]

 [[ 902.46022902  655.18997784  474.43533652]
  [ 655.18997784  819.36802818  769.96067372]
  [ 474.43533652  769.96067372  901.36266108]]

 [[  85.11134475  1

In [66]:
labels = gmm.predict(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)